### PR TITLE
Merges changes from 1.3.X into master

### PR DESCRIPTION
**Pull request by Potherca**
Fixes Travis build by making sure the locales used in the tests are installed on the Travis environment.

### CODE REVIEW

**Comment by Ocramius** [comment]
Looks good, but needs a rebase

**Comment by potherca** [comment]
I got the feeling I was missing something :disappointed:. Will rebase & try again.

**Comment by Potherca** [comment]
There was a conflict on `.travis.yml` between branches `1.3.x` and `master`. This is as clean as I can get it (at this hour :computer: :sleeping:).

**Comment by Ocramius** [comment]
@Potherca can you assign an appropriate milestone to this PR? As far as I know, 2.0.0 is released

**Pull request merged**
