### PR TITLE
Prevent certain editors from marking PHPTAL as a project containing errors

### PR DESCRIPTION
**Pull request by lengthofrope**
I use NetBeans on a daily basis and use PHPTAL a lot. But NetBeans always shows errors in the projects. I made a little change to one of your tests to prevent these errors.

### CODE REVIEW

**Comment by lengthofrope** [comment]
Curious why Travis failed, seems to be an issue with:
PHPTAL_ConfigurationException: Language(s) code(s) "en_GB, en_GB.utf8" not supported by your system

That's not something I did, as I only updated a test which seems to work fine according to Scritinizer.

**Comment by potherca** [comment]
Thanks for taking the time to do this. I'll take a look at the Travis build over the weekend to see what the trouble is.

**Comment by potherca** [comment]
First off, there seems to be a change in the Travis platform.

>  This job ran on our new platform for Precise builds. Please read [our blog post for more information](https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future).

My first guess is that the locales (and/or the keys to identify them with) have changed.

Currently looking into this.

**Comment by potherca** [comment]
Found and fixed the problem on Travis in #50. As far as I'm concerned this can be merged.

**Pull request merged**
