### PR TITLE
Add .gitattributes to remove unneeded files

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by Potherca** [comment]
Thanks for this!

I totally forgot about ignoring files that are  irrelevant for release/deploy scenarios. As Composer also uses `.gitattributes`, this is a very useful addition in my opinion. 

@Ocramius Do you think the `Makefile` should also be added?

**Comment by Ocramius** [comment]
@Potherca yep. The XSD is still needed though, as folks download it locally to validate PHPTAL files manually.

**Comment by Slamdunk** [comment]
`Makefile` added

**Comment by Slamdunk** [comment]
@Potherca to be clear, composer doesn't use `.gitattributes`, Github do while building the zip file for download, and composer just refers to these zip files

**Comment by Potherca** [comment]
@Slamdunk Thanks for the clarification. It never hurt to be explicit :smile: 

@Ocramius This looks good to merge. Agree?

**Comment by Ocramius** [comment]
@Potherca go on :-)

**Pull request merged**
